"""SQLAlchemy ORM models."""

import enum
import uuid
from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Any

from sqlalchemy import Boolean, JSON, Date, DateTime, Enum, ForeignKey, Numeric, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    type_annotation_map = {
        dict[str, Any]: JSON,
    }


class DraftStatus(str, enum.Enum):
    """Status of a draft reply."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    SNOOZED = "snoozed"


class MessageDirection(str, enum.Enum):
    """Direction of a message."""

    INBOUND = "inbound"
    OUTBOUND = "outbound"


class FunnelStage(str, enum.Enum):
    """Sales funnel stage for a conversation."""

    INITIATED = "initiated"  # We sent outreach, no reply yet
    POSITIVE_REPLY = "positive_reply"  # Lead replied to initial message/follow-ups
    PITCHED = "pitched"  # After we invite them to schedule a call
    CALENDAR_SENT = "calendar_sent"  # They agreed to meet, we sent calendar link
    BOOKED = "booked"  # They booked into calendar
    REGENERATION = "regeneration"  # Re-engaging after drop-off


class ReplyClassification(str, enum.Enum):
    """Classification of a prospect's reply for metrics tracking."""

    POSITIVE = "positive"  # First reply was positive
    NOT_INTERESTED = "not_interested"  # Prospect not interested
    NOT_ICP = "not_icp"  # Prospect doesn't match ICP


class ProspectSource(str, enum.Enum):
    """Source of a prospect."""

    COMPETITOR_POST = "competitor_post"  # From competitor LinkedIn post engagers
    COLD_OUTREACH = "cold_outreach"  # From cold outreach keyword search
    SALES_NAV = "sales_nav"  # From LinkedIn Sales Navigator
    VAYNE = "vayne"  # From Vayne leads
    BUYING_SIGNAL = "buying_signal"  # From Gojiberry buying signal agent
    MANUAL = "manual"  # Manually added
    OTHER = "other"


class WatchedProfileCategory(str, enum.Enum):
    """Category of a watched LinkedIn profile."""

    PROSPECT = "prospect"
    INFLUENCER = "influencer"
    ICP_PEER = "icp_peer"
    COMPETITOR = "competitor"


class EngagementPostStatus(str, enum.Enum):
    """Status of an engagement post draft."""

    PENDING = "pending"
    DONE = "done"
    EDITED = "edited"
    SKIPPED = "skipped"


class Conversation(Base):
    """A LinkedIn conversation with a lead."""

    __tablename__ = "conversations"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    heyreach_lead_id: Mapped[str] = mapped_column(String(255), index=True)
    linkedin_profile_url: Mapped[str] = mapped_column(String(500))
    lead_name: Mapped[str] = mapped_column(String(255))
    linkedin_account_id: Mapped[str | None] = mapped_column(
        String(100), nullable=True
    )  # sender.id from HeyReach webhook, needed to send messages
    conversation_history: Mapped[list[dict[str, Any]] | None] = mapped_column(
        JSON,
        default=list,
        nullable=True,
    )
    funnel_stage: Mapped[FunnelStage | None] = mapped_column(
        Enum(
            FunnelStage,
            name="funnel_stage",
            values_callable=lambda x: [e.value for e in x],
        ),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    drafts: Mapped[list["Draft"]] = relationship(back_populates="conversation")
    messages: Mapped[list["MessageLog"]] = relationship(back_populates="conversation")


class Draft(Base):
    """A draft reply generated by AI for user approval."""

    __tablename__ = "drafts"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("conversations.id"),
        index=True,
    )
    status: Mapped[DraftStatus] = mapped_column(
        Enum(
            DraftStatus,
            name="draft_status",
            values_callable=lambda x: [e.value for e in x],
        ),
        default=DraftStatus.PENDING,
    )
    ai_draft: Mapped[str] = mapped_column(Text)
    slack_message_ts: Mapped[str | None] = mapped_column(String(50), nullable=True)
    snooze_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    # The outbound message that triggered this reply
    triggering_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Classification for metrics
    is_first_reply: Mapped[bool] = mapped_column(default=False)
    classification: Mapped[ReplyClassification | None] = mapped_column(
        Enum(
            ReplyClassification,
            name="reply_classification",
            values_callable=lambda x: [e.value for e in x],
        ),
        nullable=True,
    )
    classified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    conversation: Mapped["Conversation"] = relationship(back_populates="drafts")


class MessageLog(Base):
    """A log entry for a message in a conversation."""

    __tablename__ = "message_log"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("conversations.id"),
        index=True,
    )
    direction: Mapped[MessageDirection] = mapped_column(
        Enum(
            MessageDirection,
            name="message_direction",
            values_callable=lambda x: [e.value for e in x],
        ),
    )
    content: Mapped[str] = mapped_column(Text)
    sent_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    campaign_id: Mapped[int | None] = mapped_column(nullable=True)
    campaign_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Relationships
    conversation: Mapped["Conversation"] = relationship(back_populates="messages")


class Prospect(Base):
    """A prospect scraped and sent to HeyReach for outreach.

    Tracks the full lifecycle: scraped -> sent to HeyReach -> replied -> conversation.
    """

    __tablename__ = "prospects"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    # LinkedIn identifier - unique, used to link to conversations
    linkedin_url: Mapped[str] = mapped_column(String(500), unique=True, index=True)

    # Lead info
    full_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    first_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    last_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    job_title: Mapped[str | None] = mapped_column(String(255), nullable=True)
    company_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    company_industry: Mapped[str | None] = mapped_column(String(255), nullable=True)
    location: Mapped[str | None] = mapped_column(String(255), nullable=True)
    headline: Mapped[str | None] = mapped_column(Text, nullable=True)
    email: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)

    # Activity scoring (for gift leads / prospect pool reuse)
    connection_count: Mapped[int | None] = mapped_column(nullable=True)
    follower_count: Mapped[int | None] = mapped_column(nullable=True)
    is_creator: Mapped[bool | None] = mapped_column(nullable=True)
    activity_score: Mapped[float | None] = mapped_column(Numeric(8, 2), nullable=True)

    # Source tracking
    source_type: Mapped[ProspectSource] = mapped_column(
        Enum(
            ProspectSource,
            name="prospect_source",
            values_callable=lambda x: [e.value for e in x],
        ),
        default=ProspectSource.OTHER,
    )
    source_keyword: Mapped[str | None] = mapped_column(String(255), nullable=True)  # e.g., "ceo", "cold outreach"
    source_post_url: Mapped[str | None] = mapped_column(String(500), nullable=True)  # LinkedIn post they engaged with

    # Engagement context
    engagement_type: Mapped[str | None] = mapped_column(String(50), nullable=True)  # LIKE, INTEREST, CELEBRATE, etc.
    engagement_comment: Mapped[str | None] = mapped_column(Text, nullable=True)  # Their comment if applicable
    post_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)  # When the post was made
    scraped_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)  # When we scraped them

    # Outreach data
    personalized_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    prompt_version_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("prompt_versions.id"),
        nullable=True,
    )
    icp_match: Mapped[bool | None] = mapped_column(nullable=True)
    icp_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # HeyReach tracking
    heyreach_list_id: Mapped[int | None] = mapped_column(nullable=True)
    heyreach_uploaded_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Follow-up list tracking (for automatic removal on reply)
    followup_list_id: Mapped[int | None] = mapped_column(nullable=True)
    added_to_followup_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Link to conversation (when they reply)
    conversation_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("conversations.id"),
        nullable=True,
        index=True,
    )

    # Positive reply tracking
    positive_reply_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    positive_reply_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Connection tracking
    connection_sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    connection_accepted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Funnel stage tracking
    pitched_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    calendar_sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    booked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Pitched channel tracking
    pitched_slack_ts: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    conversation: Mapped["Conversation | None"] = relationship()


class ICPFeedback(Base):
    """Feedback for ICP refinement when a prospect is marked as Not ICP.

    This data is exported to multichannel-outreach for ICP analysis and improvement.
    """

    __tablename__ = "icp_feedback"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    # Lead info snapshot
    lead_name: Mapped[str] = mapped_column(String(255))
    linkedin_url: Mapped[str] = mapped_column(String(500), index=True)
    job_title: Mapped[str | None] = mapped_column(String(255), nullable=True)
    company_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Original ICP assessment (from Prospect table)
    original_icp_match: Mapped[bool | None] = mapped_column(nullable=True)
    original_icp_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # User feedback
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    marked_by_slack_user: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Link to draft that was classified
    draft_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("drafts.id"),
        nullable=True,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )


class DailyMetrics(Base):
    """Daily aggregated metrics for reporting.

    Stores metrics from all three projects:
    - speed_to_lead: Conversation and funnel metrics (calculated from DB)
    - multichannel-outreach: Outreach pipeline metrics (POSTed)
    - contentCreator: Content creation metrics (POSTed)
    """

    __tablename__ = "daily_metrics"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    date: Mapped[date] = mapped_column(Date, unique=True, index=True)

    # Outreach metrics (from multichannel-outreach)
    posts_scraped: Mapped[int] = mapped_column(default=0)
    profiles_scraped: Mapped[int] = mapped_column(default=0)
    icp_qualified: Mapped[int] = mapped_column(default=0)
    heyreach_uploaded: Mapped[int] = mapped_column(default=0)
    apify_cost: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    deepseek_cost: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))

    # Engagement metrics (from engagement monitoring)
    engagement_apify_cost: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    engagement_deepseek_cost: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    engagement_checks: Mapped[int] = mapped_column(default=0)
    engagement_posts_found: Mapped[int] = mapped_column(default=0)

    # Content metrics (from contentCreator)
    content_drafts_created: Mapped[int] = mapped_column(default=0)
    content_drafts_scheduled: Mapped[int] = mapped_column(default=0)
    content_drafts_posted: Mapped[int] = mapped_column(default=0)
    hooks_generated: Mapped[int] = mapped_column(default=0)
    ideas_added: Mapped[int] = mapped_column(default=0)

    # Speed metrics
    avg_speed_to_lead_minutes: Mapped[int | None] = mapped_column(nullable=True)
    speed_to_lead_count: Mapped[int] = mapped_column(default=0)
    avg_speed_to_reply_minutes: Mapped[int | None] = mapped_column(nullable=True)
    speed_to_reply_count: Mapped[int] = mapped_column(default=0)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )


class PipelineRun(Base):
    """Record of a pipeline execution with metrics and costs."""

    __tablename__ = "pipeline_runs"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    run_type: Mapped[str] = mapped_column(String(50), index=True)  # gift_leads, competitor_post, buying_signal
    prospect_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    prospect_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    icp_description: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="started")  # started, completed, failed

    # Pipeline metrics
    queries_generated: Mapped[int] = mapped_column(default=0)
    posts_found: Mapped[int] = mapped_column(default=0)
    engagers_found: Mapped[int] = mapped_column(default=0)
    profiles_scraped: Mapped[int] = mapped_column(default=0)
    location_filtered: Mapped[int] = mapped_column(default=0)
    icp_qualified: Mapped[int] = mapped_column(default=0)
    final_leads: Mapped[int] = mapped_column(default=0)

    # Cost breakdown
    cost_apify_google: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    cost_apify_reactions: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    cost_apify_profiles: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    cost_deepseek_icp: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    cost_deepseek_personalize: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    cost_total: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))

    # API call counts
    count_google_searches: Mapped[int] = mapped_column(default=0)
    count_posts_scraped: Mapped[int] = mapped_column(default=0)
    count_profiles_scraped: Mapped[int] = mapped_column(default=0)
    count_icp_checks: Mapped[int] = mapped_column(default=0)
    count_personalizations: Mapped[int] = mapped_column(default=0)

    # Timing
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_seconds: Mapped[int | None] = mapped_column(nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )


class WatchedProfile(Base):
    """A LinkedIn profile to monitor for engagement opportunities."""

    __tablename__ = "watched_profiles"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    linkedin_url: Mapped[str] = mapped_column(String(500), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(255))
    headline: Mapped[str | None] = mapped_column(Text, nullable=True)
    category: Mapped[WatchedProfileCategory] = mapped_column(
        Enum(
            WatchedProfileCategory,
            name="watched_profile_category",
            values_callable=lambda x: [e.value for e in x],
        ),
        default=WatchedProfileCategory.PROSPECT,
    )
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    last_checked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    engagement_posts: Mapped[list["EngagementPost"]] = relationship(
        back_populates="watched_profile"
    )


class ChangelogCategory(str, enum.Enum):
    """Category of a changelog entry."""

    PROMPT = "prompt"                    # Prompt template changes
    ICP_FILTER = "icp_filter"            # ICP criteria, hardcoded lists, thresholds
    PROSPECT_SOURCE = "prospect_source"  # New sources added/modified
    PIPELINE_CONFIG = "pipeline_config"  # Country filters, min_reactions, model params
    VALIDATION = "validation"            # Scoring thresholds, validation rules
    MODEL = "model"                      # LLM model switches
    AB_TEST = "ab_test"                  # A/B test configurations
    INFRASTRUCTURE = "infrastructure"    # New scripts, endpoints, webhooks
    HEYREACH = "heyreach"               # Campaign config, list IDs
    STAGE_PROMPT = "stage_prompt"        # Reply stage detection/generation prompts


class EngagementPost(Base):
    """A LinkedIn post found from a watched profile, with draft comment."""

    __tablename__ = "engagement_posts"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    watched_profile_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("watched_profiles.id"),
        index=True,
    )
    post_url: Mapped[str] = mapped_column(String(500), unique=True, index=True)
    post_snippet: Mapped[str | None] = mapped_column(Text, nullable=True)
    post_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    draft_comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[EngagementPostStatus] = mapped_column(
        Enum(
            EngagementPostStatus,
            name="engagement_post_status",
            values_callable=lambda x: [e.value for e in x],
        ),
        default=EngagementPostStatus.PENDING,
    )
    slack_message_ts: Mapped[str | None] = mapped_column(String(50), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    watched_profile: Mapped["WatchedProfile"] = relationship(
        back_populates="engagement_posts"
    )


class PromptVersion(Base):
    """Snapshot of a prompt template for linking to prospects."""

    __tablename__ = "prompt_versions"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    prompt_name: Mapped[str] = mapped_column(String(255), index=True)  # e.g. "LINKEDIN_5_LINE_DM_PROMPT"
    prompt_hash: Mapped[str] = mapped_column(String(64), unique=True)  # SHA256
    content: Mapped[str] = mapped_column(Text)
    git_commit: Mapped[str | None] = mapped_column(String(40), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )


class Changelog(Base):
    """Tracks all changes affecting outreach results."""

    __tablename__ = "changelog"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)  # when change happened
    category: Mapped[ChangelogCategory] = mapped_column(
        Enum(
            ChangelogCategory,
            name="changelog_category",
            values_callable=lambda x: [e.value for e in x],
        ),
    )
    component: Mapped[str] = mapped_column(String(255))  # e.g. "LINKEDIN_5_LINE_DM_PROMPT", "competitor_post_pipeline"
    change_type: Mapped[str] = mapped_column(String(50))  # added, modified, removed
    description: Mapped[str] = mapped_column(Text)
    details: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)  # structured metadata
    git_commit: Mapped[str | None] = mapped_column(String(40), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
