"""SQLAlchemy ORM models."""

import enum
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import JSON, DateTime, Enum, ForeignKey, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    type_annotation_map = {
        dict[str, Any]: JSON,
    }


class DraftStatus(str, enum.Enum):
    """Status of a draft reply."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    SNOOZED = "snoozed"


class MessageDirection(str, enum.Enum):
    """Direction of a message."""

    INBOUND = "inbound"
    OUTBOUND = "outbound"


class Conversation(Base):
    """A LinkedIn conversation with a lead."""

    __tablename__ = "conversations"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    heyreach_lead_id: Mapped[str] = mapped_column(String(255), index=True)
    linkedin_profile_url: Mapped[str] = mapped_column(String(500))
    lead_name: Mapped[str] = mapped_column(String(255))
    linkedin_account_id: Mapped[str | None] = mapped_column(
        String(100), nullable=True
    )  # sender.id from HeyReach webhook, needed to send messages
    conversation_history: Mapped[list[dict[str, Any]] | None] = mapped_column(
        JSON,
        default=list,
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    drafts: Mapped[list["Draft"]] = relationship(back_populates="conversation")
    messages: Mapped[list["MessageLog"]] = relationship(back_populates="conversation")


class Draft(Base):
    """A draft reply generated by AI for user approval."""

    __tablename__ = "drafts"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("conversations.id"),
        index=True,
    )
    status: Mapped[DraftStatus] = mapped_column(
        Enum(DraftStatus, name="draft_status"),
        default=DraftStatus.PENDING,
    )
    ai_draft: Mapped[str] = mapped_column(Text)
    slack_message_ts: Mapped[str | None] = mapped_column(String(50), nullable=True)
    snooze_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    conversation: Mapped["Conversation"] = relationship(back_populates="drafts")


class MessageLog(Base):
    """A log entry for a message in a conversation."""

    __tablename__ = "message_log"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("conversations.id"),
        index=True,
    )
    direction: Mapped[MessageDirection] = mapped_column(
        Enum(MessageDirection, name="message_direction"),
    )
    content: Mapped[str] = mapped_column(Text)
    sent_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    conversation: Mapped["Conversation"] = relationship(back_populates="messages")
